### ISSUE TITLE
@t3-oss/env-nextjs@0.6.1 incompatible types with zod

### ISSUE THREAD

**Issue by donnes** [t3-oss/t3-env#126]
`v0.6.1`

<img width="1552" alt="Screenshot 2023-09-25 at 17 42 15" src="https://github.com/t3-oss/t3-env/assets/9506146/8d58e6a4-e070-4d73-978e-29cc1116994b">

`v0.6.0`

<img width="1552" alt="Screenshot 2023-09-25 at 17 41 57" src="https://github.com/t3-oss/t3-env/assets/9506146/fce2040a-72ba-4290-a9f4-f8425554d83e">

I'm using zod `v3.22.2`

**Comment by chungweileong94** [comment]
Hmm, mind if you can create a repro? Because I didn't get the same errors with `@t3-oss/env-nextjs@0.6.1` & `zod@3.22.2`.

**Comment by juliusmarminge** [comment]
Fixed in 0.7+

**Comment by samyarkd** [comment]
@juliusmarminge i still get the same typescript with error 0.7+
